### ISSUE TITLE
Could not find robot_serial for specified vendor_name

### ISSUE THREAD

**Issue by ThoSt81** [tomrosenback/botvac#2]
Hi,

I hope you can help me with this (small?) problem.

I've been able to set everything up and the client.php seems to work as it shows the current status of my robot.
However, when I copy the TOKEN returned into \examples\robot.php along with its serial number OPSxxxxx-xxxxx I am only getting the above error message.
Am I correct that SECRET=TOKEN? Or do I need to enter something else?

I am not sure if this is because something has changed on the NEATO website or if I am doing this all wrong :)

Thanks for your help!
Thomas

**Comment by tomrosenback** [comment]
For me it works still so you must have missed something during authorization.

**Comment by ThoSt81** [comment]
Hi Tom,

thanks for your quick answer. I am looking into this again but I am failing to find the "secret" when running the client.php. I am getting all my settings so the AUTH is working. It's showing a TOKEN on top but that is changing all the time, therefore I dont think this is the secret? Can you help me once more?

Thanks!

**Comment by tomrosenback** [comment]
Getting a new token is fine, this is the way the API works. Everytime you do a AUTH request you simply login, and get a new token.

Sorry now I read your first question once more too, no TOKEN is not secret, this you see in the info from the $client->getRobots command. In the current client example file that command result is not written out but you see in the code as it loops through the robots how it uses $robot["serial"] and $robot["secret"].

**Comment by ThoSt81** [comment]
No worries and thanks for your response.
I thought that would be the case but was not successful to write out the secret :) (I am not a coder). I will give it another try later today and as my colleagues for help.

Thanks again!

**Comment by ThoSt81** [comment]
OK, got it and working like a charm :) Thanks!

**Comment by Flyingfufu** [comment]
Hello,

First of all, thanks for your work.

I have been able to get the client.php returning the data for a Kobold VR330 (after modifying the model name to VR220 in NeatoBotvacRobot.php and interverting the Neato and Vowerk manufacturer data in NeatoBotvacClient.php). However, Kobold are not returning the serial and secret information. I'm now stuck on how to run a command as I always get the subject title error message.

Hope you can help me there...

Regards,
