### ISSUE TITLE
Account banned due to too many logins - Possible Solution = Cache authorize + getRobots

### ISSUE THREAD

**Issue by anonymous-one** [tomrosenback/botvac#4]
Heya.

Thanks for the simple but great API, thought I would post my experience:

I have been using your API handler to integrate my Neato Botvac with my OpenHAB setup for about 3 weeks.

A week or so ago, I got an auto-email from Neato saying my account was banned. After talking to the support agent, he mentioned there were too many login requests.

I was pooling the status of my neato once a minute. I told him I would turn off my OpenHAB + Neato integration and they unblocked my account.

So what I have just done is basically cache the "authorize" call as well as the "getRobots" call.

Just put it together now, and its working well, we'll see if this doesn't raise any red flags on Neato's end, but essentially it skips 2 out of 3 api calls to Neato and it just recycles the active session.

I won't post my code as its slightly integrated to my OpenHAB setup, but essentially it just stores the autorize / getRobots calls to /tmp/neato.token and /tmp/neato.robots.

If possible I would recommend adding these to the API so other folks don't have to go through the same experience I went through.

On the other hand this could be done by running your API via a while(true){ ... } and just authenticating and getting the list of robots once at the start, but most people are not going to do that ;)

Anyways, thanks for the API, saved me a good few hours figuring it out myself.

EDIT :

Worth mentioning. Although I could tell this support agent was most likely not involved in the hardware or software side of their company (eg: probably strictly support role), in my initial email back to them I mentioned "this is probably because I'm logging in ever minute rather then reusing the active session". He replied by saying "yeah, the logins don't expire for 2-4 weeks". Not an exact copy paste, but he did specifically say once or twice a month.

**Comment by tomrosenback** [comment]
Yeah caching could be added to the API but also the API provides usage directly with tokens and serials without having to log back in every time using it. I will give it a thought, maybe I will add this to the API too.

Thank you for your feedback!
